### PR TITLE
Feature/api learned flag

### PR DESCRIPTION
**Pull request by gbuela**
Please review carefully! I haven't done any PHP in years :)
This is working fine in my tests. No breaking changes, just an extension of the current API to allow for sync'ing a client with the learned status of cards.

### CODE REVIEW

**Comment by fabd** [comment]
Could you update the API docs as well:

https://github.com/fabd/kanji-koohii/blob/master/apps/koohii/modules/api/templates/docsSuccess.php

(I may convert it later to markdown but atm it's plain HTML.)

**Comment by gbuela** [comment]
Yup I'll look at that tonight.
Maybe this API is not in its final form, I've been thinking of possible changes to help the client keep in sync by reducing the number of requests required, since I know that is a concern. Talk later.

**Comment by fabd** [comment]
Of course, since you are the only client of the API at the moment, we have the liberty of changing it. In fact it it makes sense to simplfy some part, remove; add something etc  as long as you can update your app go ahead.

In general the idea is to try to think outside of a single app use when designing the api endpoints.

Worst case we can have a /v2  entry point.

**Re:: Number of requests** : really depends the performance. If you use EXPLAIN and make sure the query is efficient, it is not so much of a concern. In general batch requests that act on 10+ records is a good idea.

Client side both front-end and native apps, there is the concept of "debouncing" which I haven't used yet. I will probably add such a function to my Javascript arsenal for the VueJS components. See [Throttling and debouncing](https://css-tricks.com/the-difference-between-throttling-and-debouncing/). This is mostly useful if the app features, say, some kind of toggle ability. In that case if the user keeps toggling a bunch of stuff within 1-2 seconds of each other, then the request queues it together into one request. I don't know if iOS has helpers like that.

**Comment by gbuela** [comment]
Aren't all incoming requests (web/ajax/api) from a given user throttled by the server regardless of whether they make efficient queries? I was thinking of making additional queries to return additional data for a single api call, so that I can avoid making 2 quick successive api calls. Wouldn't the second one result in an error due to the throttling?

**Comment by gbuela** [comment]
Fixed the indentation and changed the API to match the original design better. Ie getting the learned ids, instead of being a new API method, is a new variation of review/start.
Added the docs to reflect all the changes.
This API works for the app but we can still keep up the discussion above to see if it's worth trying further improvements.

**Comment by fabd** [comment]
@gbuela 
> Aren't all incoming requests (web/ajax/api) from a given user throttled by the server regardless of whether they make efficient queries?

Yes I put in a rather brutish 1 second cooldown. That was to be on the safe side due to the api being public, especially now that he code is open. So it ll probably saty for the foreseeable future.

Figuring out how to merge locally, and test via CLI.

**Comment by fabd** [comment]
@gbuela Pushed to live & staging.

Converting api/docs to docute so it's much easier to update..

**Pull request merged**
